POST 
http://localhost:8000/refresh
Content-Type: application/json

{
    token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY2YThiYjAwMjYxYTcxMDg0MzhmYTVlMyIsIm5hbWUiOiJCYXJiYXJhIE1vbnJvZSIsImxhc3RfbmFtZSI6IkZvc3RlciIsImVtYWlsIjoicGVwcGVAdGVzdC5jb20iLCJwaG9uZV9udW1iZXIiOiIrMSAoOTk1KSA3NzUtNTYyNiIsInNlbGVjdGVkX2NvdXJzZSI6Ik1vbmdvREIiLCJwYXNzd29yZCI6IiQyYiQxMCRDYkhOblNGcnpmRjlHVEhCbDl4RGNPdEh1ay84emZoWjRYWmguTEdCV3lyV2k1azh1NDdPbSIsIl9fdiI6MH0sImlhdCI6MTcyMjM0NTg3MX0.v5c7CkSaSs8ZvlLWzRVfFo5KuCi6Qv5LEoTMa8Eiq1Y
}